---
  - name: '{{task_id}}'
    hosts: testserver


    tasks:
    - name:  sync files
      synchronize: src=/Users/taoprogramer/Documents/workspace/Blog dest=/home/deploys

    - name: link uwsgi config
      shell: ln -s /home/deploys/Blog/Blog.ini /etc/uwsgi/vassals/Blog.ini
      ignore_errors: True

    - name: reload uwsgi
      shell: touch /etc/uwsgi/vassals/Blog.ini

    - name: reload nginx
      shell: nginx -s reload